### ISSUE TITLE
Alloy example?

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#31]
I have seen the [Alloy video](https://www.youtube.com/watch?v=2Uisx_Bp9l8) and I'm excited for the instant reload feature but I'm not sure how to get started with it. Is there any guide or example of how to use the new Alloy features?

**Comment by eemi2010** [comment]
This is work in progress. But  to use Alloy in your current project you just need to turn the underlying titanium project into an Alloy project. For that change in the directory where the project is and run "alloy new".

In your GWT project inherit the Alloy Module instead of the Mobile Module.

That s it :)
